# Import Modules

In [1]:
from utils import *
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np

# Validation

In [2]:
issues_df = run_validation()

Issues: 586 row(s)
 - District Issues: 127
 - Partylist Issues: 205
 - Referendum Issues: 254

# Clean Data

In [3]:
dfs_district = []
dfs_partylist = []
dfs_referendum = []

for file_config in OCR_FILES:
    total_pages = file_config["pages"]
    if "district" in file_config["path"]: 
        for page_num in range(1, total_pages, 2):
            df_dict = load_ocr_clean_data(file_config["path"], page_num)
            dfs_district.append(df_dict)
            
    elif "partylist" in file_config["path"]:
        for page_num in range(1, total_pages, 4):
            df_dict = load_ocr_clean_data(file_config["path"], page_num)
            dfs_partylist.append(df_dict)
            
    elif "referendum" in file_config["path"]:
        for page_num in range(1, total_pages, 2):
            df_dict = load_ocr_clean_data(file_config["path"], page_num)
            dfs_referendum.append(df_dict)

In [4]:
district_summary, district_scores = flatten_district(
    dfs_district
)
partylist_summary, partylist_scores = flatten_partylist(
    dfs_partylist
)
referendum_summary, referendum_scores = flatten_referendum(
    dfs_referendum
)

district_scores["คะแนน"] = pd.to_numeric(district_scores["คะแนน"], errors="coerce").fillna(0).astype(int)
partylist_scores["คะแนน"] = pd.to_numeric(partylist_scores["คะแนน"], errors="coerce").fillna(0).astype(int)
referendum_scores["คะแนน"] = pd.to_numeric(referendum_scores["คะแนน"], errors="coerce").fillna(0).astype(int)

In [5]:
district_summary.tail(5)

,unit_key,อำเภอ,ตำบล,หน่วย,จำนวนบัตรทั้งหมด,บัตรดี,บัตรเสีย,ไม่เลือกผู้ใด
274,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,18,480,274,17,3
275,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,19,200,131,4,3
276,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,20,420,256,10,9
277,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,21,440,287,15,11
278,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,400,212,15,9

In [6]:
district_scores.tail(10)

,unit_key,อำเภอ,ตำบล,หน่วย,ชื่อผู้สมัคร,พรรค,คะแนน
2222,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,21,นายนาท ฉัพพรรณธนกูร,กล้าธรรม,1
2223,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,21,นายอิทธิพัทธ์ ภักดีเนติพันธุ์,เศรษฐกิจ,6
2224,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,นายภาคภูมิ โภคทรัพย์,ประชาธิปัตย์,2
2225,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,นายพีรภัทร ทองธีรสกุล,เพื่อไทย,13
2226,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,นายธนายุทธ ยืนยั่ง,ประชาชน,45
2227,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,นางสุทธิลักษณ์ ยายิรัมย์,รวมไทยสร้างชาติ,2
2228,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,นายสนอง เทพอักษรณรงค์,ภูมิใจไทย,145
2229,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,นายวิเชียร ลานทอง,ประชากรไทย,1
2230,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,นายนาท ฉัพพรรณธนกูร,กล้าธรรม,3
2231,district/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองตา...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,นายอิทธิพัทธ์ ภักดีเนติพันธุ์,เศรษฐกิจ,1

In [7]:
partylist_summary.tail(5)

,unit_key,อำเภอ,ตำบล,หน่วย,จำนวนบัตรทั้งหมด,บัตรดี,บัตรเสีย,ไม่เลือกผู้ใด
274,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,18,480,269,23,4
275,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,19,200,201,13,0
276,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,20,420,248,7,1
277,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,21,440,295,11,1
278,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,400,208,18,10

In [8]:
partylist_scores.tail(10)

,unit_key,อำเภอ,ตำบล,หน่วย,พรรค,คะแนน
15893,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,ไทยสร้างไทย,1
15894,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,ไทยก้าวใหม่,0
15895,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,ประชาอาสาชาติ,0
15896,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,พร้อม,0
15897,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,เครือข่ายชาวนาแห่งประเทศไทย,0
15898,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,ไทยพิทักษ์ธรรม,0
15899,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,ความหวังใหม่,0
15900,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,ไทยรวมไทย,0
15901,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,เพื่อบ้านเมือง,0
15902,partylist/ontime/อำเภอเมืองบุรีรัมย์/ตำบลหนองต...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,พลังไทยรักชาติ,0

In [9]:
referendum_summary.tail(5)

,unit_key,อำเภอ,ตำบล,หน่วย,ผู้มีสิทธิ,ผู้มาใช้สิทธิ,บัตรเสีย
267,referendum/inside/อำเภอเมืองบุรีรัมย์/ตำบลหนอง...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,18,486,0,11
268,referendum/inside/อำเภอเมืองบุรีรัมย์/ตำบลหนอง...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,19,213,138,2
269,referendum/inside/อำเภอเมืองบุรีรัมย์/ตำบลหนอง...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,20,535,256,6
270,referendum/inside/อำเภอเมืองบุรีรัมย์/ตำบลหนอง...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,21,459,313,11
271,referendum/inside/อำเภอเมืองบุรีรัมย์/ตำบลหนอง...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,198,236,9

In [10]:
referendum_scores.tail(5)

,unit_key,อำเภอ,ตำบล,หน่วย,รายการ,คะแนน
811,referendum/inside/อำเภอเมืองบุรีรัมย์/ตำบลหนอง...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,21,ไม่เห็นชอบ,86
812,referendum/inside/อำเภอเมืองบุรีรัมย์/ตำบลหนอง...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,21,ไม่แสดงความคิดเห็น,39
813,referendum/inside/อำเภอเมืองบุรีรัมย์/ตำบลหนอง...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,เห็นชอบ,124
814,referendum/inside/อำเภอเมืองบุรีรัมย์/ตำบลหนอง...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,ไม่เห็นชอบ,80
815,referendum/inside/อำเภอเมืองบุรีรัมย์/ตำบลหนอง...,อำเภอเมืองบุรีรัมย์,ตำบลหนองตาด,22,ไม่แสดงความคิดเห็น,23

In [11]:
district_summary.to_csv("flatten_result/district_summary.csv")
district_scores.to_csv("flatten_result/district_scores.csv")
partylist_summary.to_csv("flatten_result/partylist_summary.csv")
partylist_scores.to_csv("flatten_result/partylist_scores.csv")
referendum_summary.to_csv("flatten_result/referendum_summary.csv")
referendum_scores.to_csv("flatten_result/referendum_scores.csv")